<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class KabupatenSeeder extends Seeder
{
    /**
     * Get data of all 416 Kabupaten in Indonesia.
     */
    public function getData(): array
    {
        return [
            [11, 'Kabupaten Simeulue', 'kabupaten'],
            [11, 'Kabupaten Aceh Singkil', 'kabupaten'],
            [11, 'Kabupaten Aceh Selatan', 'kabupaten'],
            [11, 'Kabupaten Aceh Tenggara', 'kabupaten'],
            [11, 'Kabupaten Aceh Timur', 'kabupaten'],
            [11, 'Kabupaten Aceh Tengah', 'kabupaten'],
            [11, 'Kabupaten Aceh Barat', 'kabupaten'],
            [11, 'Kabupaten Aceh Besar', 'kabupaten'],
            [11, 'Kabupaten Pidie', 'kabupaten'],
            [11, 'Kabupaten Bireuen', 'kabupaten'],
            [11, 'Kabupaten Aceh Utara', 'kabupaten'],
            [11, 'Kabupaten Aceh Barat Daya', 'kabupaten'],
            [11, 'Kabupaten Gayo Lues', 'kabupaten'],
            [11, 'Kabupaten Aceh Tamiang', 'kabupaten'],
            [11, 'Kabupaten Nagan Raya', 'kabupaten'],
            [11, 'Kabupaten Aceh Jaya', 'kabupaten'],
            [11, 'Kabupaten Bener Meriah', 'kabupaten'],
            [11, 'Kabupaten Pidie Jaya', 'kabupaten'],
            [12, 'Kabupaten Nias', 'kabupaten'],
            [12, 'Kabupaten Mandailing Natal', 'kabupaten'],
            [12, 'Kabupaten Tapanuli Selatan', 'kabupaten'],
            [12, 'Kabupaten Tapanuli Tengah', 'kabupaten'],
            [12, 'Kabupaten Tapanuli Utara', 'kabupaten'],
            [12, 'Kabupaten Toba', 'kabupaten'],
            [12, 'Kabupaten Labuhanbatu', 'kabupaten'],
            [12, 'Kabupaten Asahan', 'kabupaten'],
            [12, 'Kabupaten Simalungun', 'kabupaten'],
            [12, 'Kabupaten Dairi', 'kabupaten'],
            [12, 'Kabupaten Karo', 'kabupaten'],
            [12, 'Kabupaten Deli Serdang', 'kabupaten'],
            [12, 'Kabupaten Langkat', 'kabupaten'],
            [12, 'Kabupaten Nias Selatan', 'kabupaten'],
            [12, 'Kabupaten Humbang Hasundutan', 'kabupaten'],
            [12, 'Kabupaten Pakpak Bharat', 'kabupaten'],
            [12, 'Kabupaten Samosir', 'kabupaten'],
            [12, 'Kabupaten Serdang Bedagai', 'kabupaten'],
            [12, 'Kabupaten Batu Bara', 'kabupaten'],
            [12, 'Kabupaten Padang Lawas Utara', 'kabupaten'],
            [12, 'Kabupaten Padang Lawas', 'kabupaten'],
            [12, 'Kabupaten Labuhanbatu Selatan', 'kabupaten'],
            [12, 'Kabupaten Labuhanbatu Utara', 'kabupaten'],
            [12, 'Kabupaten Nias Utara', 'kabupaten'],
            [12, 'Kabupaten Nias Barat', 'kabupaten'],
            [13, 'Kabupaten Kepulauan Mentawai', 'kabupaten'],
            [13, 'Kabupaten Pesisir Selatan', 'kabupaten'],
            [13, 'Kabupaten Solok', 'kabupaten'],
            [13, 'Kabupaten Sijunjung', 'kabupaten'],
            [13, 'Kabupaten Tanah Datar', 'kabupaten'],
            [13, 'Kabupaten Padang Pariaman', 'kabupaten'],
            [13, 'Kabupaten Agam', 'kabupaten'],
            [13, 'Kabupaten Lima Puluh Kota', 'kabupaten'],
            [13, 'Kabupaten Pasaman', 'kabupaten'],
            [13, 'Kabupaten Solok Selatan', 'kabupaten'],
            [13, 'Kabupaten Dharmasraya', 'kabupaten'],
            [13, 'Kabupaten Pasaman Barat', 'kabupaten'],
            [14, 'Kabupaten Kuantan Singingi', 'kabupaten'],
            [14, 'Kabupaten Indragiri Hulu', 'kabupaten'],
            [14, 'Kabupaten Indragiri Hilir', 'kabupaten'],
            [14, 'Kabupaten Pelalawan', 'kabupaten'],
            [14, 'Kabupaten Siak', 'kabupaten'],
            [14, 'Kabupaten Kampar', 'kabupaten'],
            [14, 'Kabupaten Rokan Hulu', 'kabupaten'],
            [14, 'Kabupaten Bengkalis', 'kabupaten'],
            [14, 'Kabupaten Rokan Hilir', 'kabupaten'],
            [14, 'Kabupaten Kepulauan Meranti', 'kabupaten'],
            [15, 'Kabupaten Kerinci', 'kabupaten'],
            [15, 'Kabupaten Merangin', 'kabupaten'],
            [15, 'Kabupaten Sarolangun', 'kabupaten'],
            [15, 'Kabupaten Batanghari', 'kabupaten'],
            [15, 'Kabupaten Muaro Jambi', 'kabupaten'],
            [15, 'Kabupaten Tanjung Jabung Barat', 'kabupaten'],
            [15, 'Kabupaten Tanjung Jabung Timur', 'kabupaten'],
            [15, 'Kabupaten Bungo', 'kabupaten'],
            [15, 'Kabupaten Tebo', 'kabupaten'],
            [16, 'Kabupaten Ogan Komering Ulu', 'kabupaten'],
            [16, 'Kabupaten Ogan Komering Ilir', 'kabupaten'],
            [16, 'Kabupaten Muara Enim', 'kabupaten'],
            [16, 'Kabupaten Lahat', 'kabupaten'],
            [16, 'Kabupaten Musi Rawas', 'kabupaten'],
            [16, 'Kabupaten Musi Banyuasin', 'kabupaten'],
            [16, 'Kabupaten Banyuasin', 'kabupaten'],
            [16, 'Kabupaten Ogan Komering Ulu Timur', 'kabupaten'],
            [16, 'Kabupaten Ogan Komering Ulu Selatan', 'kabupaten'],
            [16, 'Kabupaten Ogan Ilir', 'kabupaten'],
            [16, 'Kabupaten Empat Lawang', 'kabupaten'],
            [16, 'Kabupaten Penukal Abab Lematang Ilir', 'kabupaten'],
            [16, 'Kabupaten Musi Rawas Utara', 'kabupaten'],
            [17, 'Kabupaten Bengkulu Selatan', 'kabupaten'],
            [17, 'Kabupaten Rejang Lebong', 'kabupaten'],
            [17, 'Kabupaten Bengkulu Utara', 'kabupaten'],
            [17, 'Kabupaten Kaur', 'kabupaten'],
            [17, 'Kabupaten Seluma', 'kabupaten'],
            [17, 'Kabupaten Mukomuko', 'kabupaten'],
            [17, 'Kabupaten Lebong', 'kabupaten'],
            [17, 'Kabupaten Kepahiang', 'kabupaten'],
            [17, 'Kabupaten Bengkulu Tengah', 'kabupaten'],
            [18, 'Kabupaten Lampung Barat', 'kabupaten'],
            [18, 'Kabupaten Tanggamus', 'kabupaten'],
            [18, 'Kabupaten Lampung Selatan', 'kabupaten'],
            [18, 'Kabupaten Lampung Timur', 'kabupaten'],
            [18, 'Kabupaten Lampung Tengah', 'kabupaten'],
            [18, 'Kabupaten Lampung Utara', 'kabupaten'],
            [18, 'Kabupaten Way Kanan', 'kabupaten'],
            [18, 'Kabupaten Tulang Bawang', 'kabupaten'],
            [18, 'Kabupaten Pesawaran', 'kabupaten'],
            [18, 'Kabupaten Pringsewu', 'kabupaten'],
            [18, 'Kabupaten Mesuji', 'kabupaten'],
            [18, 'Kabupaten Tulang Bawang Barat', 'kabupaten'],
            [18, 'Kabupaten Pesisir Barat', 'kabupaten'],
            [19, 'Kabupaten Bangka', 'kabupaten'],
            [19, 'Kabupaten Belitung', 'kabupaten'],
            [19, 'Kabupaten Bangka Barat', 'kabupaten'],
            [19, 'Kabupaten Bangka Tengah', 'kabupaten'],
            [19, 'Kabupaten Bangka Selatan', 'kabupaten'],
            [19, 'Kabupaten Belitung Timur', 'kabupaten'],
            [21, 'Kabupaten Karimun', 'kabupaten'],
            [21, 'Kabupaten Bintan', 'kabupaten'],
            [21, 'Kabupaten Natuna', 'kabupaten'],
            [21, 'Kabupaten Lingga', 'kabupaten'],
            [21, 'Kabupaten Kepulauan Anambas', 'kabupaten'],
            [31, 'Kabupaten Administrasi Kepulauan Seribu', 'kabupaten'],
            [32, 'Kabupaten Bogor', 'kabupaten'],
            [32, 'Kabupaten Sukabumi', 'kabupaten'],
            [32, 'Kabupaten Cianjur', 'kabupaten'],
            [32, 'Kabupaten Bandung', 'kabupaten'],
            [32, 'Kabupaten Garut', 'kabupaten'],
            [32, 'Kabupaten Tasikmalaya', 'kabupaten'],
            [32, 'Kabupaten Ciamis', 'kabupaten'],
            [32, 'Kabupaten Kuningan', 'kabupaten'],
            [32, 'Kabupaten Cirebon', 'kabupaten'],
            [32, 'Kabupaten Majalengka', 'kabupaten'],
            [32, 'Kabupaten Sumedang', 'kabupaten'],
            [32, 'Kabupaten Indramayu', 'kabupaten'],
            [32, 'Kabupaten Subang', 'kabupaten'],
            [32, 'Kabupaten Purwakarta', 'kabupaten'],
            [32, 'Kabupaten Karawang', 'kabupaten'],
            [32, 'Kabupaten Bekasi', 'kabupaten'],
            [32, 'Kabupaten Bandung Barat', 'kabupaten'],
            [32, 'Kabupaten Pangandaran', 'kabupaten'],
            [33, 'Kabupaten Cilacap', 'kabupaten'],
            [33, 'Kabupaten Banyumas', 'kabupaten'],
            [33, 'Kabupaten Purbalingga', 'kabupaten'],
            [33, 'Kabupaten Banjarnegara', 'kabupaten'],
            [33, 'Kabupaten Kebumen', 'kabupaten'],
            [33, 'Kabupaten Purworejo', 'kabupaten'],
            [33, 'Kabupaten Wonosobo', 'kabupaten'],
            [33, 'Kabupaten Magelang', 'kabupaten'],
            [33, 'Kabupaten Boyolali', 'kabupaten'],
            [33, 'Kabupaten Klaten', 'kabupaten'],
            [33, 'Kabupaten Sukoharjo', 'kabupaten'],
            [33, 'Kabupaten Wonogiri', 'kabupaten'],
            [33, 'Kabupaten Karanganyar', 'kabupaten'],
            [33, 'Kabupaten Sragen', 'kabupaten'],
            [33, 'Kabupaten Grobogan', 'kabupaten'],
            [33, 'Kabupaten Blora', 'kabupaten'],
            [33, 'Kabupaten Rembang', 'kabupaten'],
            [33, 'Kabupaten Pati', 'kabupaten'],
            [33, 'Kabupaten Kudus', 'kabupaten'],
            [33, 'Kabupaten Jepara', 'kabupaten'],
            [33, 'Kabupaten Demak', 'kabupaten'],
            [33, 'Kabupaten Semarang', 'kabupaten'],
            [33, 'Kabupaten Temanggung', 'kabupaten'],
            [33, 'Kabupaten Kendal', 'kabupaten'],
            [33, 'Kabupaten Batang', 'kabupaten'],
            [33, 'Kabupaten Pekalongan', 'kabupaten'],
            [33, 'Kabupaten Pemalang', 'kabupaten'],
            [33, 'Kabupaten Tegal', 'kabupaten'],
            [33, 'Kabupaten Brebes', 'kabupaten'],
            [34, 'Kabupaten Kulon Progo', 'kabupaten'],
            [34, 'Kabupaten Bantul', 'kabupaten'],
            [34, 'Kabupaten Gunungkidul', 'kabupaten'],
            [34, 'Kabupaten Sleman', 'kabupaten'],
            [35, 'Kabupaten Pacitan', 'kabupaten'],
            [35, 'Kabupaten Ponorogo', 'kabupaten'],
            [35, 'Kabupaten Trenggalek', 'kabupaten'],
            [35, 'Kabupaten Tulungagung', 'kabupaten'],
            [35, 'Kabupaten Blitar', 'kabupaten'],
            [35, 'Kabupaten Kediri', 'kabupaten'],
            [35, 'Kabupaten Malang', 'kabupaten'],
            [35, 'Kabupaten Lumajang', 'kabupaten'],
            [35, 'Kabupaten Jember', 'kabupaten'],
            [35, 'Kabupaten Banyuwangi', 'kabupaten'],
            [35, 'Kabupaten Bondowoso', 'kabupaten'],
            [35, 'Kabupaten Situbondo', 'kabupaten'],
            [35, 'Kabupaten Probolinggo', 'kabupaten'],
            [35, 'Kabupaten Pasuruan', 'kabupaten'],
            [35, 'Kabupaten Sidoarjo', 'kabupaten'],
            [35, 'Kabupaten Mojokerto', 'kabupaten'],
            [35, 'Kabupaten Jombang', 'kabupaten'],
            [35, 'Kabupaten Nganjuk', 'kabupaten'],
            [35, 'Kabupaten Madiun', 'kabupaten'],
            [35, 'Kabupaten Magetan', 'kabupaten'],
            [35, 'Kabupaten Ngawi', 'kabupaten'],
            [35, 'Kabupaten Bojonegoro', 'kabupaten'],
            [35, 'Kabupaten Tuban', 'kabupaten'],
            [35, 'Kabupaten Lamongan', 'kabupaten'],
            [35, 'Kabupaten Gresik', 'kabupaten'],
            [35, 'Kabupaten Bangkalan', 'kabupaten'],
            [35, 'Kabupaten Sampang', 'kabupaten'],
            [35, 'Kabupaten Pamekasan', 'kabupaten'],
            [35, 'Kabupaten Sumenep', 'kabupaten'],
            [36, 'Kabupaten Pandeglang', 'kabupaten'],
            [36, 'Kabupaten Lebak', 'kabupaten'],
            [36, 'Kabupaten Tangerang', 'kabupaten'],
            [36, 'Kabupaten Serang', 'kabupaten'],
            [51, 'Kabupaten Jembrana', 'kabupaten'],
            [51, 'Kabupaten Tabanan', 'kabupaten'],
            [51, 'Kabupaten Badung', 'kabupaten'],
            [51, 'Kabupaten Gianyar', 'kabupaten'],
            [51, 'Kabupaten Klungkung', 'kabupaten'],
            [51, 'Kabupaten Bangli', 'kabupaten'],
            [51, 'Kabupaten Karangasem', 'kabupaten'],
            [51, 'Kabupaten Buleleng', 'kabupaten'],
            [52, 'Kabupaten Lombok Barat', 'kabupaten'],
            [52, 'Kabupaten Lombok Tengah', 'kabupaten'],
            [52, 'Kabupaten Lombok Timur', 'kabupaten'],
            [52, 'Kabupaten Sumbawa', 'kabupaten'],
            [52, 'Kabupaten Dompu', 'kabupaten'],
            [52, 'Kabupaten Bima', 'kabupaten'],
            [52, 'Kabupaten Sumbawa Barat', 'kabupaten'],
            [52, 'Kabupaten Lombok Utara', 'kabupaten'],
            [53, 'Kabupaten Sumba Barat', 'kabupaten'],
            [53, 'Kabupaten Sumba Timur', 'kabupaten'],
            [53, 'Kabupaten Kupang', 'kabupaten'],
            [53, 'Kabupaten Timor Tengah Selatan', 'kabupaten'],
            [53, 'Kabupaten Timor Tengah Utara', 'kabupaten'],
            [53, 'Kabupaten Belu', 'kabupaten'],
            [53, 'Kabupaten Alor', 'kabupaten'],
            [53, 'Kabupaten Lembata', 'kabupaten'],
            [53, 'Kabupaten Flores Timur', 'kabupaten'],
            [53, 'Kabupaten Sikka', 'kabupaten'],
            [53, 'Kabupaten Ende', 'kabupaten'],
            [53, 'Kabupaten Ngada', 'kabupaten'],
            [53, 'Kabupaten Manggarai', 'kabupaten'],
            [53, 'Kabupaten Rote Ndao', 'kabupaten'],
            [53, 'Kabupaten Manggarai Barat', 'kabupaten'],
            [53, 'Kabupaten Sumba Tengah', 'kabupaten'],
            [53, 'Kabupaten Sumba Barat Daya', 'kabupaten'],
            [53, 'Kabupaten Nagekeo', 'kabupaten'],
            [53, 'Kabupaten Manggarai Timur', 'kabupaten'],
            [53, 'Kabupaten Sabu Raijua', 'kabupaten'],
            [53, 'Kabupaten Malaka', 'kabupaten'],
            [61, 'Kabupaten Sambas', 'kabupaten'],
            [61, 'Kabupaten Bengkayang', 'kabupaten'],
            [61, 'Kabupaten Landak', 'kabupaten'],
            [61, 'Kabupaten Mempawah', 'kabupaten'],
            [61, 'Kabupaten Sanggau', 'kabupaten'],
            [61, 'Kabupaten Ketapang', 'kabupaten'],
            [61, 'Kabupaten Sintang', 'kabupaten'],
            [61, 'Kabupaten Kapuas Hulu', 'kabupaten'],
            [61, 'Kabupaten Sekadau', 'kabupaten'],
            [61, 'Kabupaten Melawi', 'kabupaten'],
            [61, 'Kabupaten Kayong Utara', 'kabupaten'],
            [61, 'Kabupaten Kubu Raya', 'kabupaten'],
            [62, 'Kabupaten Kotawaringin Barat', 'kabupaten'],
            [62, 'Kabupaten Kotawaringin Timur', 'kabupaten'],
            [62, 'Kabupaten Kapuas', 'kabupaten'],
            [62, 'Kabupaten Barito Selatan', 'kabupaten'],
            [62, 'Kabupaten Barito Utara', 'kabupaten'],
            [62, 'Kabupaten Sukamara', 'kabupaten'],
            [62, 'Kabupaten Lamandau', 'kabupaten'],
            [62, 'Kabupaten Seruyan', 'kabupaten'],
            [62, 'Kabupaten Katingan', 'kabupaten'],
            [62, 'Kabupaten Pulang Pisau', 'kabupaten'],
            [62, 'Kabupaten Gunung Mas', 'kabupaten'],
            [62, 'Kabupaten Barito Timur', 'kabupaten'],
            [62, 'Kabupaten Murung Raya', 'kabupaten'],
            [63, 'Kabupaten Tanah Laut', 'kabupaten'],
            [63, 'Kabupaten Kotabaru', 'kabupaten'],
            [63, 'Kabupaten Banjar', 'kabupaten'],
            [63, 'Kabupaten Barito Kuala', 'kabupaten'],
            [63, 'Kabupaten Tapin', 'kabupaten'],
            [63, 'Kabupaten Hulu Sungai Selatan', 'kabupaten'],
            [63, 'Kabupaten Hulu Sungai Tengah', 'kabupaten'],
            [63, 'Kabupaten Hulu Sungai Utara', 'kabupaten'],
            [63, 'Kabupaten Tabalong', 'kabupaten'],
            [63, 'Kabupaten Tanah Bumbu', 'kabupaten'],
            [63, 'Kabupaten Balangan', 'kabupaten'],
            [64, 'Kabupaten Paser', 'kabupaten'],
            [64, 'Kabupaten Kutai Barat', 'kabupaten'],
            [64, 'Kabupaten Kutai Kartanegara', 'kabupaten'],
            [64, 'Kabupaten Kutai Timur', 'kabupaten'],
            [64, 'Kabupaten Berau', 'kabupaten'],
            [64, 'Kabupaten Penajam Paser Utara', 'kabupaten'],
            [64, 'Kabupaten Mahakam Ulu', 'kabupaten'],
            [65, 'Kabupaten Malinau', 'kabupaten'],
            [65, 'Kabupaten Bulungan', 'kabupaten'],
            [65, 'Kabupaten Tana Tidung', 'kabupaten'],
            [65, 'Kabupaten Nunukan', 'kabupaten'],
            [71, 'Kabupaten Bolaang Mongondow', 'kabupaten'],
            [71, 'Kabupaten Minahasa', 'kabupaten'],
            [71, 'Kabupaten Kepulauan Sangihe', 'kabupaten'],
            [71, 'Kabupaten Kepulauan Talaud', 'kabupaten'],
            [71, 'Kabupaten Minahasa Selatan', 'kabupaten'],
            [71, 'Kabupaten Minahasa Utara', 'kabupaten'],
            [71, 'Kabupaten Bolaang Mongondow Utara', 'kabupaten'],
            [71, 'Kabupaten Siau Tagulandang Biaro', 'kabupaten'],
            [71, 'Kabupaten Minahasa Tenggara', 'kabupaten'],
            [71, 'Kabupaten Bolaang Mongondow Selatan', 'kabupaten'],
            [71, 'Kabupaten Bolaang Mongondow Timur', 'kabupaten'],
            [72, 'Kabupaten Banggai Kepulauan', 'kabupaten'],
            [72, 'Kabupaten Banggai', 'kabupaten'],
            [72, 'Kabupaten Morowali', 'kabupaten'],
            [72, 'Kabupaten Poso', 'kabupaten'],
            [72, 'Kabupaten Donggala', 'kabupaten'],
            [72, 'Kabupaten Toli-Toli', 'kabupaten'],
            [72, 'Kabupaten Buol', 'kabupaten'],
            [72, 'Kabupaten Parigi Moutong', 'kabupaten'],
            [72, 'Kabupaten Tojo Una-Una', 'kabupaten'],
            [72, 'Kabupaten Sigi', 'kabupaten'],
            [72, 'Kabupaten Banggai Laut', 'kabupaten'],
            [72, 'Kabupaten Morowali Utara', 'kabupaten'],
            [73, 'Kabupaten Kepulauan Selayar', 'kabupaten'],
            [73, 'Kabupaten Bulukumba', 'kabupaten'],
            [73, 'Kabupaten Bantaeng', 'kabupaten'],
            [73, 'Kabupaten Jeneponto', 'kabupaten'],
            [73, 'Kabupaten Takalar', 'kabupaten'],
            [73, 'Kabupaten Gowa', 'kabupaten'],
            [73, 'Kabupaten Sinjai', 'kabupaten'],
            [73, 'Kabupaten Maros', 'kabupaten'],
            [73, 'Kabupaten Pangkajene dan Kepulauan', 'kabupaten'],
            [73, 'Kabupaten Barru', 'kabupaten'],
            [73, 'Kabupaten Bone', 'kabupaten'],
            [73, 'Kabupaten Soppeng', 'kabupaten'],
            [73, 'Kabupaten Wajo', 'kabupaten'],
            [73, 'Kabupaten Sidenreng Rappang', 'kabupaten'],
            [73, 'Kabupaten Pinrang', 'kabupaten'],
            [73, 'Kabupaten Enrekang', 'kabupaten'],
            [73, 'Kabupaten Luwu', 'kabupaten'],
            [73, 'Kabupaten Tana Toraja', 'kabupaten'],
            [73, 'Kabupaten Luwu Utara', 'kabupaten'],
            [73, 'Kabupaten Luwu Timur', 'kabupaten'],
            [73, 'Kabupaten Toraja Utara', 'kabupaten'],
            [74, 'Kabupaten Buton', 'kabupaten'],
            [74, 'Kabupaten Muna', 'kabupaten'],
            [74, 'Kabupaten Konawe', 'kabupaten'],
            [74, 'Kabupaten Kolaka', 'kabupaten'],
            [74, 'Kabupaten Konawe Selatan', 'kabupaten'],
            [74, 'Kabupaten Bombana', 'kabupaten'],
            [74, 'Kabupaten Wakatobi', 'kabupaten'],
            [74, 'Kabupaten Kolaka Utara', 'kabupaten'],
            [74, 'Kabupaten Buton Utara', 'kabupaten'],
            [74, 'Kabupaten Konawe Utara', 'kabupaten'],
            [74, 'Kabupaten Kolaka Timur', 'kabupaten'],
            [74, 'Kabupaten Konawe Kepulauan', 'kabupaten'],
            [74, 'Kabupaten Muna Barat', 'kabupaten'],
            [74, 'Kabupaten Buton Tengah', 'kabupaten'],
            [74, 'Kabupaten Buton Selatan', 'kabupaten'],
            [75, 'Kabupaten Boalemo', 'kabupaten'],
            [75, 'Kabupaten Gorontalo', 'kabupaten'],
            [75, 'Kabupaten Pohuwato', 'kabupaten'],
            [75, 'Kabupaten Bone Bolango', 'kabupaten'],
            [75, 'Kabupaten Gorontalo Utara', 'kabupaten'],
            [76, 'Kabupaten Pasangkayu', 'kabupaten'],
            [76, 'Kabupaten Mamuju', 'kabupaten'],
            [76, 'Kabupaten Mamasa', 'kabupaten'],
            [76, 'Kabupaten Polewali Mandar', 'kabupaten'],
            [76, 'Kabupaten Majene', 'kabupaten'],
            [76, 'Kabupaten Mamuju Tengah', 'kabupaten'],
            [81, 'Kabupaten Kepulauan Tanimbar', 'kabupaten'],
            [81, 'Kabupaten Maluku Tenggara', 'kabupaten'],
            [81, 'Kabupaten Maluku Tengah', 'kabupaten'],
            [81, 'Kabupaten Buru', 'kabupaten'],
            [81, 'Kabupaten Kepulauan Aru', 'kabupaten'],
            [81, 'Kabupaten Seram Bagian Barat', 'kabupaten'],
            [81, 'Kabupaten Seram Bagian Timur', 'kabupaten'],
            [81, 'Kabupaten Maluku Barat Daya', 'kabupaten'],
            [81, 'Kabupaten Buru Selatan', 'kabupaten'],
            [82, 'Kabupaten Halmahera Barat', 'kabupaten'],
            [82, 'Kabupaten Halmahera Tengah', 'kabupaten'],
            [82, 'Kabupaten Kepulauan Sula', 'kabupaten'],
            [82, 'Kabupaten Halmahera Selatan', 'kabupaten'],
            [82, 'Kabupaten Halmahera Utara', 'kabupaten'],
            [82, 'Kabupaten Halmahera Timur', 'kabupaten'],
            [82, 'Kabupaten Pulau Morotai', 'kabupaten'],
            [82, 'Kabupaten Pulau Taliabu', 'kabupaten'],
            [91, 'Kabupaten Fakfak', 'kabupaten'],
            [91, 'Kabupaten Kaimana', 'kabupaten'],
            [91, 'Kabupaten Teluk Wondama', 'kabupaten'],
            [91, 'Kabupaten Teluk Bintuni', 'kabupaten'],
            [91, 'Kabupaten Manokwari', 'kabupaten'],
            [91, 'Kabupaten Manokwari Selatan', 'kabupaten'],
            [91, 'Kabupaten Pegunungan Arfak', 'kabupaten'],
            [92, 'Kabupaten Jayapura', 'kabupaten'],
            [92, 'Kabupaten Kepulauan Yapen', 'kabupaten'],
            [92, 'Kabupaten Biak Numfor', 'kabupaten'],
            [92, 'Kabupaten Sarmi', 'kabupaten'],
            [92, 'Kabupaten Keerom', 'kabupaten'],
            [92, 'Kabupaten Waropen', 'kabupaten'],
            [92, 'Kabupaten Supiori', 'kabupaten'],
            [92, 'Kabupaten Mamberamo Raya', 'kabupaten'],
            [93, 'Kabupaten Merauke', 'kabupaten'],
            [93, 'Kabupaten Boven Digoel', 'kabupaten'],
            [93, 'Kabupaten Mappi', 'kabupaten'],
            [93, 'Kabupaten Asmat', 'kabupaten'],
            [94, 'Kabupaten Nabire', 'kabupaten'],
            [94, 'Kabupaten Puncak Jaya', 'kabupaten'],
            [94, 'Kabupaten Paniai', 'kabupaten'],
            [94, 'Kabupaten Mimika', 'kabupaten'],
            [94, 'Kabupaten Puncak', 'kabupaten'],
            [94, 'Kabupaten Dogiyai', 'kabupaten'],
            [94, 'Kabupaten Intan Jaya', 'kabupaten'],
            [94, 'Kabupaten Deiyai', 'kabupaten'],
            [95, 'Kabupaten Jayawijaya', 'kabupaten'],
            [95, 'Kabupaten Pegunungan Bintang', 'kabupaten'],
            [95, 'Kabupaten Yahukimo', 'kabupaten'],
            [95, 'Kabupaten Tolikara', 'kabupaten'],
            [95, 'Kabupaten Mamberamo Tengah', 'kabupaten'],
            [95, 'Kabupaten Yalimo', 'kabupaten'],
            [95, 'Kabupaten Lanny Jaya', 'kabupaten'],
            [95, 'Kabupaten Nduga', 'kabupaten'],
            [96, 'Kabupaten Sorong', 'kabupaten'],
            [96, 'Kabupaten Sorong Selatan', 'kabupaten'],
            [96, 'Kabupaten Raja Ampat', 'kabupaten'],
            [96, 'Kabupaten Tambrauw', 'kabupaten'],
            [96, 'Kabupaten Maybrat', 'kabupaten'],
        ];
    }

    /**
     * Run the database seeds for Kabupaten.
     */
    public function run(): void
    {
        $now = Carbon::now();
        $raw = $this->getData();

        $kabupatens = [];
        foreach ($raw as $item) {
            $kabupatens[] = [
                'province_id' => $item[0],
                'name' => $item[1],
                'type' => $item[2],
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }

        // Avoid duplicate seeding if already populated
        if (DB::table('regencies')->where('type', 'kabupaten')->count() === 0) {
            foreach (array_chunk($kabupatens, 100) as $chunk) {
                DB::table('regencies')->insert($chunk);
            }
        }
    }
}
